language: ruby

env:
  - DB=sqlite3
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - rake test
before_script:
  - cp config/database.yml config/database.yml
bundler_args: --binstubs=./bundler_stubs
