language: ruby

env:
  - DB=sqlite3
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - rake test
before_script:
  - cp config/database.yml config/database.yml
  - bundle lock --add-platform x86-mingw32 x86-mswin32
